server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: tourtpuser-service
          uri: http://localhost:8081
          predicates:
            - Path=/toucan/rtp/user/**
          filters:
            - AuthenticationFilter
            
        - id: jwttoken-1-service
          uri: http://localhost:8083
          predicates:
            - Path=/authenticate/**
          
        - id: student-service
          uri: http://localhost:8085
          predicates:
            - Path=/student/**
#          filters:
#            - AuthenticationFilter
